import type { Meta, StoryObj } from '@storybook/vue3';
import TokenList from '@tokens/components/tokens/token-list/token-list.vue';

const meta: Meta<typeof TokenList> = {
  title: 'Tokens/TokenList',
  component: TokenList,
  tags: ['autodocs'],
  args: {
    debug: false,
    isDisabledUI: false,
    diceList: [],
    listToken: [
      {
        index: 0,
        positionGame: 'BOTTOM_LEFT',
        tokens: [
          {
            color: 'RED',
            coordinate: { x: 156, y: 234 },
            typeTile: 'NORMAL',
            positionTile: 4,
            index: 0,
            diceAvailable: [],
            totalTokens: 1,
            position: 1,
            enableTooltip: false,
            isMoving: false,
            animated: false,
            canSelectToken: false,
          },
          {
            color: 'RED',
            coordinate: { x: 130, y: 208 },
            typeTile: 'NORMAL',
            positionTile: 5,
            index: 1,
            diceAvailable: [],
            totalTokens: 1,
            position: 1,
            enableTooltip: false,
            isMoving: false,
            animated: false,
            canSelectToken: false,
          },
          {
            color: 'RED',
            coordinate: { x: 196, y: 211 },
            typeTile: 'END',
            positionTile: 2,
            index: 2,
            diceAvailable: [],
            totalTokens: 1,
            position: 1,
            enableTooltip: false,
            isMoving: false,
            animated: false,
            canSelectToken: false,
          },
          {
            color: 'RED',
            coordinate: { x: 182, y: 197 },
            typeTile: 'END',
            positionTile: 3,
            index: 3,
            diceAvailable: [],
            totalTokens: 1,
            position: 1,
            enableTooltip: false,
            isMoving: false,
            animated: false,
            canSelectToken: false,
          },
        ],
      },
      {
        index: 1,
        positionGame: 'TOP_LEFT',
        tokens: [
          {
            color: 'GREEN',
            coordinate: { x: 39, y: 39 },
            typeTile: 'JAIL',
            positionTile: 0,
            index: 0,
            diceAvailable: [],
            totalTokens: 1,
            position: 1,
            enableTooltip: false,
            isMoving: false,
            animated: false,
            canSelectToken: false,
          },
          {
            color: 'GREEN',
            coordinate: { x: 153, y: 182 },
            typeTile: 'END',
            positionTile: 1,
            index: 1,
            diceAvailable: [],
            totalTokens: 1,
            position: 1,
            enableTooltip: false,
            isMoving: false,
            animated: false,
            canSelectToken: false,
          },
          {
            color: 'GREEN',
            coordinate: { x: 91, y: 39 },
            typeTile: 'JAIL',
            positionTile: 2,
            index: 2,
            diceAvailable: [],
            totalTokens: 1,
            position: 1,
            enableTooltip: false,
            isMoving: false,
            animated: false,
            canSelectToken: false,
          },
          {
            color: 'GREEN',
            coordinate: { x: 208, y: 312 },
            typeTile: 'NORMAL',
            positionTile: 47,
            index: 3,
            diceAvailable: [],
            totalTokens: 1,
            position: 1,
            enableTooltip: false,
            isMoving: false,
            animated: false,
            canSelectToken: false,
          },
        ],
      },
      {
        index: 2,
        positionGame: 'TOP_RIGHT',
        tokens: [
          {
            color: 'YELLOW',
            coordinate: { x: 273, y: 39 },
            typeTile: 'JAIL',
            positionTile: 0,
            index: 0,
            diceAvailable: [{ key: 0.8884305185720938, value: 6 }],
            totalTokens: 1,
            position: 1,
            enableTooltip: false,
            isMoving: false,
            animated: true,
            canSelectToken: false,
          },
          {
            color: 'YELLOW',
            coordinate: { x: 52, y: 208 },
            typeTile: 'NORMAL',
            positionTile: 8,
            index: 1,
            diceAvailable: [
              { key: 0.8884305185720938, value: 6 },
              { key: 0.3417396335373841, value: 5 },
            ],
            totalTokens: 1,
            position: 1,
            enableTooltip: false,
            isMoving: false,
            animated: false,
            canSelectToken: false,
          },
          {
            color: 'YELLOW',
            coordinate: { x: 312, y: 156 },
            typeTile: 'NORMAL',
            positionTile: 34,
            index: 2,
            diceAvailable: [
              { key: 0.8884305185720938, value: 6 },
              { key: 0.3417396335373841, value: 5 },
            ],
            totalTokens: 2,
            position: 1,
            enableTooltip: false,
            isMoving: false,
            animated: false,
            canSelectToken: false,
          },
          {
            color: 'YELLOW',
            coordinate: { x: 325, y: 91 },
            typeTile: 'JAIL',
            positionTile: 3,
            index: 3,
            diceAvailable: [{ key: 0.8884305185720938, value: 6 }],
            totalTokens: 1,
            position: 1,
            enableTooltip: false,
            isMoving: false,
            animated: false,
            canSelectToken: false,
          },
        ],
      },
      {
        index: 3,
        positionGame: 'BOTTOM_RIGHT',
        tokens: [
          {
            color: 'BLUE',
            coordinate: { x: 211, y: 196 },
            typeTile: 'END',
            positionTile: 0,
            index: 0,
            diceAvailable: [],
            totalTokens: 1,
            position: 1,
            enableTooltip: false,
            isMoving: false,
            animated: false,
            canSelectToken: false,
          },
          {
            color: 'BLUE',
            coordinate: { x: 338, y: 208 },
            typeTile: 'NORMAL',
            positionTile: 39,
            index: 1,
            diceAvailable: [],
            totalTokens: 1,
            position: 1,
            enableTooltip: false,
            isMoving: false,
            animated: false,
            canSelectToken: false,
          },
          {
            color: 'BLUE',
            coordinate: { x: 286, y: 208 },
            typeTile: 'NORMAL',
            positionTile: 41,
            index: 2,
            diceAvailable: [],
            totalTokens: 1,
            position: 1,
            enableTooltip: false,
            isMoving: false,
            animated: false,
            canSelectToken: false,
          },
          {
            color: 'BLUE',
            coordinate: { x: 312, y: 156 },
            typeTile: 'NORMAL',
            positionTile: 34,
            index: 3,
            diceAvailable: [],
            totalTokens: 2,
            position: 2,
            enableTooltip: false,
            isMoving: false,
            animated: false,
            canSelectToken: false,
          },
        ],
      },
    ],
  },
};

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {},
};
