import type { IListTokens } from '@tokens/interfaces/token.interface';

export const TOKENS_JAIL_AND_OUTSITE: IListTokens[] = [
  {
    index: 0,
    positionGame: 'BOTTOM_LEFT',
    tokens: [
      {
        color: 'RED',
        coordinate: { x: 168, y: 211 },
        typeTile: 'END',
        positionTile: 0,
        index: 0,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: 'RED',
        coordinate: { x: 182, y: 234 },
        typeTile: 'EXIT',
        positionTile: 4,
        index: 1,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: 'RED',
        coordinate: { x: 182, y: 211 },
        typeTile: 'END',
        positionTile: 1,
        index: 2,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: 'RED',
        coordinate: { x: 196, y: 211 },
        typeTile: 'END',
        positionTile: 2,
        index: 3,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
    ],
  },
  {
    index: 1,
    positionGame: 'TOP_LEFT',
    tokens: [
      {
        color: 'GREEN',
        coordinate: { x: 153, y: 168 },
        typeTile: 'END',
        positionTile: 0,
        index: 0,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: 'GREEN',
        coordinate: { x: 153, y: 182 },
        typeTile: 'END',
        positionTile: 1,
        index: 1,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: 'GREEN',
        coordinate: { x: 130, y: 182 },
        typeTile: 'EXIT',
        positionTile: 4,
        index: 2,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: 'GREEN',
        coordinate: { x: 153, y: 196 },
        typeTile: 'END',
        positionTile: 2,
        index: 3,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
    ],
  },
  {
    index: 2,
    positionGame: 'TOP_RIGHT',
    tokens: [
      {
        color: 'YELLOW',
        coordinate: { x: 196, y: 153 },
        typeTile: 'END',
        positionTile: 0,
        index: 0,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: 'YELLOW',
        coordinate: { x: 182, y: 130 },
        typeTile: 'EXIT',
        positionTile: 4,
        index: 1,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: 'YELLOW',
        coordinate: { x: 182, y: 153 },
        typeTile: 'END',
        positionTile: 1,
        index: 2,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: 'YELLOW',
        coordinate: { x: 168, y: 153 },
        typeTile: 'END',
        positionTile: 2,
        index: 3,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
    ],
  },
  {
    index: 3,
    positionGame: 'BOTTOM_RIGHT',
    tokens: [
      {
        color: 'BLUE',
        coordinate: { x: 234, y: 182 },
        typeTile: 'EXIT',
        positionTile: 4,
        index: 0,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: 'BLUE',
        coordinate: { x: 211, y: 196 },
        typeTile: 'END',
        positionTile: 0,
        index: 1,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: 'BLUE',
        coordinate: { x: 211, y: 182 },
        typeTile: 'END',
        positionTile: 1,
        index: 2,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: 'BLUE',
        coordinate: { x: 197, y: 182 },
        typeTile: 'END',
        positionTile: 3,
        index: 3,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
    ],
  },
];
