import type { IListTokens } from '@/modules/tokens/interfaces/token';

export const TOKENS_JAIL_AND_OUTSITE: IListTokens[] = [
  {
    index: 0,
    positionGame: 'BOTTOM_LEFT',
    tokens: [
      {
        color: 'RED',
        coordinate: { x: 182, y: 234 },
        typeTile: 'EXIT',
        positionTile: 4,
        index: 0,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: 'RED',
        coordinate: { x: 182, y: 260 },
        typeTile: 'EXIT',
        positionTile: 3,
        index: 1,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: 'RED',
        coordinate: { x: 182, y: 286 },
        typeTile: 'EXIT',
        positionTile: 2,
        index: 2,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: 'RED',
        coordinate: { x: 182, y: 312 },
        typeTile: 'EXIT',
        positionTile: 1,
        index: 3,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
    ],
  },
  {
    index: 1,
    positionGame: 'TOP_LEFT',
    tokens: [
      {
        color: 'GREEN',
        coordinate: { x: 130, y: 182 },
        typeTile: 'EXIT',
        positionTile: 4,
        index: 0,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: false,
      },
      {
        color: 'GREEN',
        coordinate: { x: 104, y: 182 },
        typeTile: 'EXIT',
        positionTile: 3,
        index: 1,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: false,
      },
      {
        color: 'GREEN',
        coordinate: { x: 78, y: 182 },
        typeTile: 'EXIT',
        positionTile: 2,
        index: 2,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: false,
      },
      {
        color: 'GREEN',
        coordinate: { x: 52, y: 182 },
        typeTile: 'EXIT',
        positionTile: 1,
        index: 3,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: false,
      },
    ],
  },
  {
    index: 2,
    positionGame: 'TOP_RIGHT',
    tokens: [
      {
        color: 'YELLOW',
        coordinate: { x: 182, y: 130 },
        typeTile: 'EXIT',
        positionTile: 4,
        index: 0,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: false,
      },
      {
        color: 'YELLOW',
        coordinate: { x: 182, y: 104 },
        typeTile: 'EXIT',
        positionTile: 3,
        index: 1,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: false,
      },
      {
        color: 'YELLOW',
        coordinate: { x: 182, y: 78 },
        typeTile: 'EXIT',
        positionTile: 2,
        index: 2,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: false,
      },
      {
        color: 'YELLOW',
        coordinate: { x: 182, y: 52 },
        typeTile: 'EXIT',
        positionTile: 1,
        index: 3,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: false,
      },
    ],
  },
  {
    index: 3,
    positionGame: 'BOTTOM_RIGHT',
    tokens: [
      {
        color: 'BLUE',
        coordinate: { x: 234, y: 182 },
        typeTile: 'EXIT',
        positionTile: 4,
        index: 0,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: false,
      },
      {
        color: 'BLUE',
        coordinate: { x: 260, y: 182 },
        typeTile: 'EXIT',
        positionTile: 3,
        index: 1,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: false,
      },
      {
        color: 'BLUE',
        coordinate: { x: 286, y: 182 },
        typeTile: 'EXIT',
        positionTile: 2,
        index: 2,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: false,
      },
      {
        color: 'BLUE',
        coordinate: { x: 312, y: 182 },
        typeTile: 'EXIT',
        positionTile: 1,
        index: 3,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: false,
      },
    ],
  },
];
