import type { IListTokens } from '@tokens/interfaces/token.interface';

export const TOKENS_JAIL_AND_OUTSITE: IListTokens[] = [
  {
    index: 0,
    positionGame: 'BOTTOM_LEFT',
    tokens: [
      {
        color: 'RED',
        coordinate: { x: 182, y: 234 },
        typeTile: 'EXIT',
        positionTile: 4,
        index: 0,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: 'RED',
        coordinate: { x: 182, y: 211 },
        typeTile: 'END',
        positionTile: 1,
        index: 1,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: 'RED',
        coordinate: { x: 196, y: 211 },
        typeTile: 'END',
        positionTile: 2,
        index: 2,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: 'RED',
        coordinate: { x: 168, y: 211 },
        typeTile: 'END',
        positionTile: 0,
        index: 3,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
    ],
  },
  {
    index: 1,
    positionGame: 'TOP_LEFT',
    tokens: [
      {
        color: 'GREEN',
        coordinate: { x: 153, y: 168 },
        typeTile: 'END',
        positionTile: 0,
        index: 0,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: 'GREEN',
        coordinate: { x: 104, y: 182 },
        typeTile: 'EXIT',
        positionTile: 3,
        index: 1,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: 'GREEN',
        coordinate: { x: 153, y: 196 },
        typeTile: 'END',
        positionTile: 2,
        index: 2,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: 'GREEN',
        coordinate: { x: 167, y: 182 },
        typeTile: 'END',
        positionTile: 3,
        index: 3,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
    ],
  },
  {
    index: 2,
    positionGame: 'TOP_RIGHT',
    tokens: [
      {
        color: 'YELLOW',
        coordinate: { x: 196, y: 153 },
        typeTile: 'END',
        positionTile: 0,
        index: 0,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: 'YELLOW',
        coordinate: { x: 182, y: 153 },
        typeTile: 'END',
        positionTile: 1,
        index: 1,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: 'YELLOW',
        coordinate: { x: 168, y: 153 },
        typeTile: 'END',
        positionTile: 2,
        index: 2,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: 'YELLOW',
        coordinate: { x: 182, y: 104 },
        typeTile: 'EXIT',
        positionTile: 3,
        index: 3,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: true,
        canSelectToken: true,
      },
    ],
  },
  {
    index: 3,
    positionGame: 'BOTTOM_RIGHT',
    tokens: [
      {
        color: 'BLUE',
        coordinate: { x: 208, y: 312 },
        typeTile: 'NORMAL',
        positionTile: 47,
        index: 0,
        diceAvailable: [{ key: 0.604036539766464, value: 1 }],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: 'BLUE',
        coordinate: { x: 286, y: 208 },
        typeTile: 'NORMAL',
        positionTile: 41,
        index: 1,
        diceAvailable: [{ key: 0.604036539766464, value: 1 }],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: 'BLUE',
        coordinate: { x: 325, y: 273 },
        typeTile: 'JAIL',
        positionTile: 2,
        index: 2,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: 'BLUE',
        coordinate: { x: 312, y: 208 },
        typeTile: 'NORMAL',
        positionTile: 40,
        index: 3,
        diceAvailable: [{ key: 0.604036539766464, value: 1 }],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
    ],
  },
];
