import type { IListTokens } from '@tokens/interfaces/token.interface';

export const TOKENS_JAIL_AND_OUTSITE: IListTokens[] = [
  {
    index: 0,
    positionGame: 'BOTTOM_LEFT',
    tokens: [
      {
        color: 'RED',
        coordinate: { x: 168, y: 211 },
        typeTile: 'END',
        positionTile: 0,
        index: 0,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: 'RED',
        coordinate: { x: 182, y: 211 },
        typeTile: 'END',
        positionTile: 1,
        index: 1,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: 'RED',
        coordinate: { x: 182, y: 197 },
        typeTile: 'END',
        positionTile: 3,
        index: 2,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: 'RED',
        coordinate: { x: 182, y: 286 },
        typeTile: 'EXIT',
        positionTile: 2,
        index: 3,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
    ],
  },
  {
    index: 1,
    positionGame: 'TOP_RIGHT',
    tokens: [
      {
        color: 'YELLOW',
        coordinate: { x: 273, y: 39 },
        typeTile: 'JAIL',
        positionTile: 0,
        index: 0,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: 'YELLOW',
        coordinate: { x: 273, y: 91 },
        typeTile: 'JAIL',
        positionTile: 1,
        index: 1,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: 'YELLOW',
        coordinate: { x: 260, y: 156 },
        typeTile: 'NORMAL',
        positionTile: 32,
        index: 2,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: 'YELLOW',
        coordinate: { x: 325, y: 91 },
        typeTile: 'JAIL',
        positionTile: 3,
        index: 3,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
    ],
  },
];
